package inventario;

/**
 *
 * @author JMorales
 */
public class PanelParaMoviles extends javax.swing.JPanel {

    /**
     * Creates new form PanelParaEquiposDeEscritorioYLaptops
     */
    public PanelParaMoviles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel17 = new javax.swing.JPanel();
        tituloEmpresa = new javax.swing.JLabel();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        txtCelular = new javax.swing.JTextField();
        filler43 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel35 = new javax.swing.JPanel();
        tituloEmpresa3 = new javax.swing.JLabel();
        filler39 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        cbxFunda = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel19 = new javax.swing.JPanel();
        tituloEmpresa1 = new javax.swing.JLabel();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        cbxCargador = new javax.swing.JComboBox<>();
        filler44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel36 = new javax.swing.JPanel();
        tituloEmpresa4 = new javax.swing.JLabel();
        filler40 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        cbxManosLibres = new javax.swing.JComboBox<>();

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(33333, 190));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 190));
        jPanel3.setPreferredSize(new java.awt.Dimension(528, 190));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel16.setMaximumSize(new java.awt.Dimension(3333, 190));
        jPanel16.setMinimumSize(new java.awt.Dimension(150, 190));
        jPanel16.setPreferredSize(new java.awt.Dimension(150, 190));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));
        jPanel16.add(filler18);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        tituloEmpresa.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa.setText("Numero de celular:");
        tituloEmpresa.setMaximumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa.setMinimumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa.setPreferredSize(new java.awt.Dimension(335, 23));
        jPanel17.add(tituloEmpresa);

        jPanel16.add(jPanel17);
        jPanel16.add(filler19);

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtCelular.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        txtCelular.setMaximumSize(new java.awt.Dimension(335, 40));
        txtCelular.setMinimumSize(new java.awt.Dimension(335, 40));
        txtCelular.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel16.add(txtCelular);
        jPanel16.add(filler43);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel35.setLayout(new java.awt.GridLayout(1, 0));

        tituloEmpresa3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa3.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa3.setText("Funda:");
        tituloEmpresa3.setMaximumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa3.setMinimumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa3.setPreferredSize(new java.awt.Dimension(335, 23));
        jPanel35.add(tituloEmpresa3);

        jPanel16.add(jPanel35);
        jPanel16.add(filler39);

        cbxFunda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        cbxFunda.setMaximumSize(new java.awt.Dimension(335, 40));
        cbxFunda.setMinimumSize(new java.awt.Dimension(335, 40));
        cbxFunda.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel16.add(cbxFunda);

        jPanel3.add(jPanel16);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel18.setMaximumSize(new java.awt.Dimension(3333, 190));
        jPanel18.setMinimumSize(new java.awt.Dimension(150, 190));
        jPanel18.setPreferredSize(new java.awt.Dimension(150, 190));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.Y_AXIS));
        jPanel18.add(filler20);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel19.setLayout(new java.awt.GridLayout());

        tituloEmpresa1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa1.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa1.setText("Cargador:");
        tituloEmpresa1.setMaximumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa1.setMinimumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa1.setPreferredSize(new java.awt.Dimension(335, 23));
        jPanel19.add(tituloEmpresa1);

        jPanel18.add(jPanel19);
        jPanel18.add(filler21);

        cbxCargador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        cbxCargador.setMaximumSize(new java.awt.Dimension(335, 40));
        cbxCargador.setMinimumSize(new java.awt.Dimension(335, 40));
        cbxCargador.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel18.add(cbxCargador);
        jPanel18.add(filler44);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel36.setLayout(new java.awt.GridLayout());

        tituloEmpresa4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa4.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa4.setText("Manos libres:");
        tituloEmpresa4.setMaximumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa4.setMinimumSize(new java.awt.Dimension(335, 23));
        tituloEmpresa4.setPreferredSize(new java.awt.Dimension(335, 23));
        jPanel36.add(tituloEmpresa4);

        jPanel18.add(jPanel36);
        jPanel18.add(filler40);

        cbxManosLibres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        cbxManosLibres.setMaximumSize(new java.awt.Dimension(335, 40));
        cbxManosLibres.setMinimumSize(new java.awt.Dimension(335, 40));
        cbxManosLibres.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel18.add(cbxManosLibres);

        jPanel3.add(jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbxCargador;
    private javax.swing.JComboBox<String> cbxFunda;
    private javax.swing.JComboBox<String> cbxManosLibres;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler39;
    private javax.swing.Box.Filler filler40;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler44;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JLabel tituloEmpresa;
    private javax.swing.JLabel tituloEmpresa1;
    private javax.swing.JLabel tituloEmpresa3;
    private javax.swing.JLabel tituloEmpresa4;
    private javax.swing.JTextField txtCelular;
    // End of variables declaration//GEN-END:variables
}
