/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventario;

/**
 *
 * @author JMorales
 */
public class PanelParaEquiposDeEscritorioYLaptops extends javax.swing.JPanel {

    /**
     * Creates new form PanelParaEquiposDeEscritorioYLaptops
     */
    public PanelParaEquiposDeEscritorioYLaptops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel17 = new javax.swing.JPanel();
        tituloEmpresa = new javax.swing.JLabel();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        txtFactura1 = new javax.swing.JTextField();
        filler43 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel35 = new javax.swing.JPanel();
        tituloEmpresa3 = new javax.swing.JLabel();
        filler44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        txtFactura5 = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        filler36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel31 = new javax.swing.JPanel();
        tituloSucursal = new javax.swing.JLabel();
        filler37 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(33333, 190));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 190));
        jPanel3.setPreferredSize(new java.awt.Dimension(528, 190));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel16.setMaximumSize(new java.awt.Dimension(3333, 220));
        jPanel16.setMinimumSize(new java.awt.Dimension(94, 220));
        jPanel16.setPreferredSize(new java.awt.Dimension(94, 220));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));
        jPanel16.add(filler18);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        tituloEmpresa.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa.setText("Nombre de equipo:");
        tituloEmpresa.setMaximumSize(new java.awt.Dimension(335, 40));
        jPanel17.add(tituloEmpresa);

        jPanel16.add(jPanel17);
        jPanel16.add(filler19);

        txtFactura1.setBackground(new java.awt.Color(255, 255, 255));
        txtFactura1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFactura1.setForeground(new java.awt.Color(0, 0, 0));
        txtFactura1.setMaximumSize(new java.awt.Dimension(335, 40));
        txtFactura1.setMinimumSize(new java.awt.Dimension(335, 40));
        txtFactura1.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel16.add(txtFactura1);
        jPanel16.add(filler43);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel35.setLayout(new java.awt.GridLayout(1, 0));

        tituloEmpresa3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloEmpresa3.setForeground(new java.awt.Color(61, 61, 61));
        tituloEmpresa3.setText("Cuenta de equipo");
        tituloEmpresa3.setMaximumSize(new java.awt.Dimension(335, 40));
        jPanel35.add(tituloEmpresa3);

        jPanel16.add(jPanel35);
        jPanel16.add(filler44);

        txtFactura5.setBackground(new java.awt.Color(255, 255, 255));
        txtFactura5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFactura5.setForeground(new java.awt.Color(0, 0, 0));
        txtFactura5.setMaximumSize(new java.awt.Dimension(335, 40));
        txtFactura5.setMinimumSize(new java.awt.Dimension(335, 40));
        txtFactura5.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel16.add(txtFactura5);

        jPanel3.add(jPanel16);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel30.setMaximumSize(new java.awt.Dimension(3333, 220));
        jPanel30.setMinimumSize(new java.awt.Dimension(94, 220));
        jPanel30.setPreferredSize(new java.awt.Dimension(94, 220));
        jPanel30.setLayout(new javax.swing.BoxLayout(jPanel30, javax.swing.BoxLayout.Y_AXIS));
        jPanel30.add(filler36);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel31.setLayout(new java.awt.GridLayout(1, 0));

        tituloSucursal.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        tituloSucursal.setForeground(new java.awt.Color(61, 61, 61));
        tituloSucursal.setText("Final de la garantía:");
        tituloSucursal.setMaximumSize(new java.awt.Dimension(335, 40));
        jPanel31.add(tituloSucursal);

        jPanel30.add(jPanel31);
        jPanel30.add(filler37);

        datePicker1.setMaximumSize(new java.awt.Dimension(335, 40));
        datePicker1.setMinimumSize(new java.awt.Dimension(335, 40));
        datePicker1.setPreferredSize(new java.awt.Dimension(335, 40));
        jPanel30.add(datePicker1);

        jPanel3.add(jPanel30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler36;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler44;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JLabel tituloEmpresa;
    private javax.swing.JLabel tituloEmpresa3;
    private javax.swing.JLabel tituloSucursal;
    private javax.swing.JTextField txtFactura1;
    private javax.swing.JTextField txtFactura5;
    // End of variables declaration//GEN-END:variables
}
