/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author JMorales
 */
public class Home extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    boolean menuDesplegado = false;

    boolean menuDesplegado2 = false;
    JButton btnSub1 = new JButton("   > Item 1");
    JButton btnSub2 = new JButton("   > Item 2");
    JButton btnSub3 = new JButton("   > Item 3");
    JButton btnSub4 = new JButton("   > Item 4");
    JButton btnSub5 = new JButton("   > Item 5");
    JButton btnSub6 = new JButton("   > Item 6");

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        this.setTitle("Sistema de Inventario - v1.0");

        this.btnHome.setIcon(crearIconoColoreado("iconos/svgs/solid/home.svg", 25, 25, Color.BLACK));
        agregarEventosHoverABoton(btnHome, crearIconoColoreado("iconos/svgs/solid/home.svg", 25, 25, Color.white), crearIconoColoreado("iconos/svgs/solid/home.svg", 25, 25, Color.BLACK), Color.BLUE, Color.WHITE);
    
        this.btnInventario.setIcon(crearIconoColoreado("iconos/svgs/solid/box-open.svg", 25, 25, Color.BLACK));
        agregarEventosHoverABoton(btnInventario, crearIconoColoreado("iconos/svgs/solid/box-open.svg", 25, 25, Color.white), crearIconoColoreado("iconos/svgs/solid/box-open.svg", 25, 25, Color.BLACK), Color.BLUE, Color.WHITE);
    
         this.btnTrabajadores.setIcon(crearIconoColoreado("iconos/svgs/solid/users.svg", 25, 25, Color.BLACK));
        agregarEventosHoverABoton(btnTrabajadores, crearIconoColoreado("iconos/svgs/solid/users.svg", 25, 25, Color.white), crearIconoColoreado("iconos/svgs/solid/users.svg", 25, 25, Color.BLACK), Color.BLUE, Color.WHITE);
    
        this.btnSubMenuOrganizacion.setIcon(crearIconoColoreado("iconos/svgs/solid/building.svg", 25, 25, Color.BLACK));
        agregarEventosHoverABoton(btnSubMenuOrganizacion, crearIconoColoreado("iconos/svgs/solid/building.svg", 25, 25, Color.white), crearIconoColoreado("iconos/svgs/solid/building.svg", 25, 25, Color.BLACK), Color.BLUE, Color.WHITE);
    
         this.subMenuConfiguracion.setIcon(crearIconoColoreado("iconos/svgs/solid/gear.svg", 25, 25, Color.BLACK));
        agregarEventosHoverABoton(subMenuConfiguracion, crearIconoColoreado("iconos/svgs/solid/gear.svg", 25, 25, Color.white), crearIconoColoreado("iconos/svgs/solid/gear.svg", 25, 25, Color.BLACK), Color.BLUE, Color.WHITE);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        btnAsignaciones = new javax.swing.JButton();
        btnSubMenuOrganizacion = new javax.swing.JButton();
        subMenuConfiguracion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 490));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 140));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(204, 0, 0));
        pnlMenu.setFocusTraversalPolicyProvider(true);
        pnlMenu.setMinimumSize(new java.awt.Dimension(93, 600));
        pnlMenu.setLayout(new java.awt.GridLayout(12, 0, 0, 1));

        btnHome.setBackground(new java.awt.Color(244, 244, 244));
        btnHome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("Home");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlMenu.add(btnHome);

        btnInventario.setBackground(new java.awt.Color(244, 244, 244));
        btnInventario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario.setText("Inventario");
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInventario);

        btnTrabajadores.setBackground(new java.awt.Color(244, 244, 244));
        btnTrabajadores.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnTrabajadores.setForeground(new java.awt.Color(51, 51, 51));
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btnTrabajadores);

        btnAsignaciones.setBackground(new java.awt.Color(244, 244, 244));
        btnAsignaciones.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAsignaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnAsignaciones.setText("Asignaciones");
        btnAsignaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAsignaciones);

        btnSubMenuOrganizacion.setBackground(new java.awt.Color(244, 244, 244));
        btnSubMenuOrganizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSubMenuOrganizacion.setForeground(new java.awt.Color(51, 51, 51));
        btnSubMenuOrganizacion.setText("subMenu1");
        btnSubMenuOrganizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubMenuOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenuOrganizacionActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSubMenuOrganizacion);

        subMenuConfiguracion.setBackground(new java.awt.Color(244, 244, 244));
        subMenuConfiguracion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        subMenuConfiguracion.setForeground(new java.awt.Color(51, 51, 51));
        subMenuConfiguracion.setText("subMenu2");
        subMenuConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subMenuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuConfiguracionActionPerformed(evt);
            }
        });
        pnlMenu.add(subMenuConfiguracion);

        jPanel2.add(pnlMenu, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(51, 0, 204));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 110));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignacionesActionPerformed

    private void btnSubMenuOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuOrganizacionActionPerformed

        int indexBoton = 4;

        if (!menuDesplegado) {
            this.pnlMenu.add(btnSub1, indexBoton + 1);
            this.pnlMenu.add(btnSub2, indexBoton + 2);
            this.pnlMenu.add(btnSub3, indexBoton + 3);

            menuDesplegado = true;

        } else {
            this.pnlMenu.remove(btnSub1);
            this.pnlMenu.remove(btnSub2);
            this.pnlMenu.remove(btnSub3);

            menuDesplegado = false;
        }

        this.pnlMenu.revalidate();
        this.pnlMenu.repaint();
    }//GEN-LAST:event_btnSubMenuOrganizacionActionPerformed

    private void subMenuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuConfiguracionActionPerformed

        int indexBoton;

        if (menuDesplegado == true) {
            indexBoton = 8;
        } else {
            indexBoton = 5;
        }

        if (!menuDesplegado2) {
            this.pnlMenu.add(btnSub4, indexBoton + 1);
            this.pnlMenu.add(btnSub5, indexBoton + 2);
            this.pnlMenu.add(btnSub6, indexBoton + 3);

            menuDesplegado2 = true;

        } else {
            this.pnlMenu.remove(btnSub4);
            this.pnlMenu.remove(btnSub5);
            this.pnlMenu.remove(btnSub6);

            menuDesplegado2 = false;
        }

        this.pnlMenu.revalidate();
        this.pnlMenu.repaint();
    }//GEN-LAST:event_subMenuConfiguracionActionPerformed

    private void agregarEventosHoverABoton(JButton boton, Icon iconoEntered, Icon iconoExited, Color colorBackground, Color colorFont) {

        boton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                boton.setIcon(iconoEntered);
                boton.setBackground(colorBackground);
                boton.setForeground(colorFont);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                boton.setIcon(iconoExited);
                boton.setBackground(Color.WHITE);
                boton.setForeground(Color.BLACK);
            }
        });

    }

    /**
     * Crea un icono SVG y fuerza que sea de un color específico.
     *
     * @param ruta Ruta dentro de resources (ej: "iconos/usuario.svg")
     * @param ancho Ancho deseado
     * @param alto Alto deseado2
     * @param colorDeseado El color que quieres (ej: Color.RED, Color.BLUE)
     * @return El icono coloreado listo para usar.
     */
    public FlatSVGIcon crearIconoColoreado(String ruta, int ancho, int alto, Color colorDeseado) {

        FlatSVGIcon icono = new FlatSVGIcon(ruta, ancho, alto);

        icono.setColorFilter(new FlatSVGIcon.ColorFilter(c -> {
            return colorDeseado;
        }));

        return icono;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignaciones;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnSubMenuOrganizacion;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JButton subMenuConfiguracion;
    // End of variables declaration//GEN-END:variables
}
