/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import Utileria.PanelRedondeado;
import Utileria.RoundedButton;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author JMorales
 */
public class Home extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    boolean menuDesplegado = false;

    boolean menuDesplegado2 = false;

    JButton btnEmpresa = new RoundedButton("   Empresas", 10);
    JButton btnSucursal = new RoundedButton("   Sucursales", 10);
    JButton btnDepartamento = new RoundedButton("   Departamentos", 10);
    JButton btnPuesto = new RoundedButton("   Puestos", 10);
    JButton btnUsuario = new RoundedButton("   Usuarios", 10);
    JButton btnAuditoria = new RoundedButton("   Auditoría", 10);

    private final Color COLOR_NORMAL = new Color(229, 231, 235);
    private final Color COLOR_HOVER = new Color(209, 213, 219);
    private final Color COLOR_SELECTED_BG = new Color(102, 204, 255);
    private final Color COLOR_SELECTED_FG = Color.WHITE;
    private final Color COLOR_TEXT_NORMAL = Color.BLACK;

    private JButton botonActual = null;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        this.setTitle("Sistema de Inventario - v1.0");

        btnHome.putClientProperty("rutaIcono", "iconos/svgs/solid/home.svg");
        configurarBotonMenu(btnHome, "iconos/svgs/solid/home.svg");

        btnInventario.putClientProperty("rutaIcono", "iconos/svgs/solid/box-open.svg");
        configurarBotonMenu(btnInventario, "iconos/svgs/solid/box-open.svg");

        btnTrabajadores.putClientProperty("rutaIcono", "iconos/svgs/solid/users.svg");
        configurarBotonMenu(btnTrabajadores, "iconos/svgs/solid/users.svg");

        btnSubMenuOrganizacion.putClientProperty("rutaIcono", "iconos/svgs/solid/building.svg");
        configurarBotonMenu(btnSubMenuOrganizacion, "iconos/svgs/solid/building.svg");

        subMenuConfiguracion.putClientProperty("rutaIcono", "iconos/svgs/solid/gear.svg");
        configurarBotonMenu(subMenuConfiguracion, "iconos/svgs/solid/gear.svg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new PanelRedondeado(15);
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnHome = new RoundedButton("Home", 15);
        btnTrabajadores = new RoundedButton("Trabajadores", 15);
        btnInventario = new RoundedButton("Inventario",15);
        btnAsignaciones = new RoundedButton("Asignaciones", 15);
        btnSubMenuOrganizacion = new RoundedButton("Organización", 15);
        subMenuConfiguracion = new RoundedButton("Configuración", 15);
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 490));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 140));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(229, 231, 235));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 20, 30, 18));
        jPanel4.setPreferredSize(new java.awt.Dimension(90, 140));
        jPanel4.setLayout(new java.awt.GridLayout());

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);

        jPanel3.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(229, 231, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 20, 1));
        jPanel6.setMinimumSize(new java.awt.Dimension(170, 82));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema TI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(126, 50));
        jPanel6.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de Inventario");
        jLabel2.setToolTipText("");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel2);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(229, 231, 235));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlMenu.setFocusTraversalPolicyProvider(true);
        pnlMenu.setMinimumSize(new java.awt.Dimension(93, 600));
        pnlMenu.setLayout(new java.awt.GridLayout(12, 0, 10, 10));

        btnHome.setBackground(new java.awt.Color(229, 231, 235));
        btnHome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("Home");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlMenu.add(btnHome);

        btnTrabajadores.setBackground(new java.awt.Color(229, 231, 235));
        btnTrabajadores.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnTrabajadores.setForeground(new java.awt.Color(51, 51, 51));
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btnTrabajadores);

        btnInventario.setBackground(new java.awt.Color(229, 231, 235));
        btnInventario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario.setText("Inventario");
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInventario);

        btnAsignaciones.setBackground(new java.awt.Color(229, 231, 235));
        btnAsignaciones.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAsignaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnAsignaciones.setText("Asignaciones");
        btnAsignaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAsignaciones);

        btnSubMenuOrganizacion.setBackground(new java.awt.Color(229, 231, 235));
        btnSubMenuOrganizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSubMenuOrganizacion.setForeground(new java.awt.Color(51, 51, 51));
        btnSubMenuOrganizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubMenuOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenuOrganizacionActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSubMenuOrganizacion);

        subMenuConfiguracion.setBackground(new java.awt.Color(229, 231, 235));
        subMenuConfiguracion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        subMenuConfiguracion.setForeground(new java.awt.Color(51, 51, 51));
        subMenuConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subMenuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuConfiguracionActionPerformed(evt);
            }
        });
        pnlMenu.add(subMenuConfiguracion);

        jPanel2.add(pnlMenu, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(51, 0, 204));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 110));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignacionesActionPerformed

    private void btnSubMenuOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuOrganizacionActionPerformed

        int indexBoton = 4;

        if (!menuDesplegado) {
            this.pnlMenu.add(btnEmpresa, indexBoton + 1);
            this.pnlMenu.add(btnSucursal, indexBoton + 2);
            this.pnlMenu.add(btnDepartamento, indexBoton + 3);
            this.pnlMenu.add(btnPuesto, indexBoton + 4);

            menuDesplegado = true;

        } else {
            this.pnlMenu.remove(btnEmpresa);
            this.pnlMenu.remove(btnSucursal);
            this.pnlMenu.remove(btnDepartamento);
            this.pnlMenu.remove(btnPuesto);

            menuDesplegado = false;
        }

        this.pnlMenu.revalidate();
        this.pnlMenu.repaint();
    }//GEN-LAST:event_btnSubMenuOrganizacionActionPerformed

    private void subMenuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuConfiguracionActionPerformed

        int indexBoton;

        if (menuDesplegado == true) {
            indexBoton = 9;
        } else {
            indexBoton = 5;
        }

        if (!menuDesplegado2) {
            this.pnlMenu.add(btnUsuario, indexBoton + 1);
            this.pnlMenu.add(btnAuditoria, indexBoton + 2);

            menuDesplegado2 = true;

        } else {
            this.pnlMenu.remove(btnUsuario);
            this.pnlMenu.remove(btnAuditoria);

            menuDesplegado2 = false;
        }

        this.pnlMenu.revalidate();
        this.pnlMenu.repaint();
    }//GEN-LAST:event_subMenuConfiguracionActionPerformed

    /**
     * Configura el comportamiento visual completo del botón (Hover, Click,
     * Selección).
     *
     * @param boton El botón a configurar.
     * @param rutaIcono La ruta del SVG (necesaria para repintarlo de
     * blanco/negro).
     */
    private void configurarBotonMenu(JButton boton, String rutaIcono) {

        boton.setBackground(COLOR_NORMAL);
        boton.setForeground(COLOR_TEXT_NORMAL);
        boton.setIcon(crearIconoColoreado(rutaIcono, 25, 25, COLOR_TEXT_NORMAL));

        boton.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                if (boton != botonActual) {
                    boton.setBackground(COLOR_HOVER);
                    boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (boton != botonActual) {
                    boton.setBackground(COLOR_NORMAL);
                }
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (botonActual != null && botonActual != boton) {
                    resetearEstiloBoton(botonActual);
                }

                botonActual = boton;
                boton.setBackground(COLOR_SELECTED_BG);
                boton.setForeground(COLOR_SELECTED_FG);
                boton.setIcon(crearIconoColoreado(rutaIcono, 25, 25, COLOR_SELECTED_FG));
            }
        });
    }

    private void resetearEstiloBoton(JButton boton) {
        boton.setBackground(COLOR_NORMAL);
        boton.setForeground(COLOR_TEXT_NORMAL);

        String ruta = (String) boton.getClientProperty("rutaIcono");
        if (ruta != null) {
            boton.setIcon(crearIconoColoreado(ruta, 25, 25, COLOR_TEXT_NORMAL));
        }
    }

    /**
     * Crea un icono SVG y fuerza que sea de un color específico.
     *
     * @param ruta Ruta dentro de resources (ej: "iconos/usuario.svg")
     * @param ancho Ancho deseado
     * @param alto Alto deseado2
     * @param colorDeseado El color que quieres (ej: Color.RED, Color.BLUE)
     * @return El icono coloreado listo para usar.
     */
    public FlatSVGIcon crearIconoColoreado(String ruta, int ancho, int alto, Color colorDeseado) {

        FlatSVGIcon icono = new FlatSVGIcon(ruta, ancho, alto);

        icono.setColorFilter(new FlatSVGIcon.ColorFilter(c -> {
            return colorDeseado;
        }));

        return icono;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignaciones;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnSubMenuOrganizacion;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JButton subMenuConfiguracion;
    // End of variables declaration//GEN-END:variables
}
