/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import Utileria.PanelRedondeado;
import Utileria.RoundedButton;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author JMorales
 */
public class Home extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    boolean menuDesplegado = false;

    boolean menuDesplegado2 = false;

    JButton btnEmpresa = new RoundedButton("Empresas", 10);
    JButton btnSucursal = new RoundedButton("Sucursales", 10);
    JButton btnDepartamento = new RoundedButton("Departamentos", 10);
    JButton btnPuesto = new RoundedButton("Puestos", 10);
    JButton btnUsuario = new RoundedButton("Usuarios", 10);
    JButton btnAuditoria = new RoundedButton("Auditoría", 10);

    private final Color COLOR_NORMAL = new Color(229, 231, 235);
    private final Color COLOR_HOVER = new Color(209, 213, 219);
    private final Color COLOR_SELECTED_BG = new Color(102, 204, 255);
    private final Color COLOR_SELECTED_FG = Color.WHITE;
    private final Color COLOR_TEXT_NORMAL = Color.BLACK;

    private JButton botonActual = null;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        this.setTitle("Sistema de Inventario - v1.0");
        
        logo.putClientProperty("rutaIcono", "iconos/svgs/logo.svg");

        btnHome.putClientProperty("rutaIcono", "iconos/svgs/regular/house.svg");
        configurarBotonMenu(btnHome, "iconos/svgs/regular/house.svg");

        btnInventario.putClientProperty("rutaIcono", "iconos/svgs/regular/clipboard.svg");
        configurarBotonMenu(btnInventario, "iconos/svgs/regular/clipboard.svg");

        btnTrabajadores.putClientProperty("rutaIcono", "iconos/svgs/regular/address-book.svg");
        configurarBotonMenu(btnTrabajadores, "iconos/svgs/regular/address-book.svg");
        
        btnAsignaciones.putClientProperty("rutaIcono", "iconos/svgs/regular/handshake.svg");
        configurarBotonMenu(btnAsignaciones, "iconos/svgs/regular/handshake.svg");

        btnSubMenuOrganizacion.putClientProperty("rutaIcono", "iconos/svgs/regular/building.svg");
        configurarBotonMenu(btnSubMenuOrganizacion, "iconos/svgs/regular/building.svg");

        subMenuConfiguracion.putClientProperty("rutaIcono", "iconos/svgs/solid/gear.svg");
        configurarBotonMenu(subMenuConfiguracion, "iconos/svgs/solid/gear.svg");

        scrollMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        configurarAlturaBotones();
        
        scrollMenu.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        
        scrollMenu.getVerticalScrollBar().setUnitIncrement(16);
    }

    private void configurarAlturaBotones() {
        // Define la altura que quieras (ej. 60px o 70px)
        java.awt.Dimension alturaBoton = new java.awt.Dimension(0, 60);

        // Aplícalo a todos tus botones
        btnHome.setPreferredSize(alturaBoton);
        btnTrabajadores.setPreferredSize(alturaBoton);
        btnInventario.setPreferredSize(alturaBoton);
        btnAsignaciones.setPreferredSize(alturaBoton);
        btnSubMenuOrganizacion.setPreferredSize(alturaBoton);
        subMenuConfiguracion.setPreferredSize(alturaBoton);

        // También a los sub-botones (btnEmpresa, btnSucursal, etc.)
        btnEmpresa.setPreferredSize(alturaBoton);
        btnSucursal.setPreferredSize(alturaBoton);
        btnDepartamento.setPreferredSize(alturaBoton);
        btnPuesto.setPreferredSize(alturaBoton);
        btnUsuario.setPreferredSize(alturaBoton);
        btnAuditoria.setPreferredSize(alturaBoton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        scrollMenu = new javax.swing.JScrollPane();
        panelInterno = new javax.swing.JPanel();
        btnHome = new RoundedButton("Home", 15);
        btnTrabajadores = new RoundedButton("Trabajadores", 15);
        btnInventario = new RoundedButton("Inventario",15);
        btnAsignaciones = new RoundedButton("Asignaciones", 15);
        btnSubMenuOrganizacion = new RoundedButton("Organización", 15);
        subMenuConfiguracion = new RoundedButton("Configuración", 15);
        piePagina = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        barraLateral.setBackground(new java.awt.Color(0, 255, 255));
        barraLateral.setAutoscrolls(true);
        barraLateral.setPreferredSize(new java.awt.Dimension(280, 490));
        barraLateral.setLayout(new java.awt.BorderLayout());

        titulo.setBackground(new java.awt.Color(229, 231, 235));
        titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        titulo.setPreferredSize(new java.awt.Dimension(280, 140));
        titulo.setLayout(new javax.swing.BoxLayout(titulo, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(229, 231, 235));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 20, 30, 18));
        jPanel4.setPreferredSize(new java.awt.Dimension(90, 140));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel4.add(logo);

        titulo.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(229, 231, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 20, 1));
        jPanel6.setMinimumSize(new java.awt.Dimension(170, 82));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema TI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(126, 50));
        jPanel6.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de Inventario");
        jLabel2.setToolTipText("");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel2);

        titulo.add(jPanel6);

        barraLateral.add(titulo, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(229, 231, 235));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlMenu.setFocusTraversalPolicyProvider(true);
        pnlMenu.setMinimumSize(new java.awt.Dimension(93, 600));
        pnlMenu.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        scrollMenu.setBorder(null);

        panelInterno.setBackground(new java.awt.Color(229, 231, 235));
        panelInterno.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        btnHome.setBackground(new java.awt.Color(229, 231, 235));
        btnHome.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("Home");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        panelInterno.add(btnHome);

        btnTrabajadores.setBackground(new java.awt.Color(229, 231, 235));
        btnTrabajadores.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnTrabajadores.setForeground(new java.awt.Color(51, 51, 51));
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        panelInterno.add(btnTrabajadores);

        btnInventario.setBackground(new java.awt.Color(229, 231, 235));
        btnInventario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnInventario.setText("Inventario");
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        panelInterno.add(btnInventario);

        btnAsignaciones.setBackground(new java.awt.Color(229, 231, 235));
        btnAsignaciones.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAsignaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnAsignaciones.setText("Asignaciones");
        btnAsignaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionesActionPerformed(evt);
            }
        });
        panelInterno.add(btnAsignaciones);

        btnSubMenuOrganizacion.setBackground(new java.awt.Color(229, 231, 235));
        btnSubMenuOrganizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSubMenuOrganizacion.setForeground(new java.awt.Color(51, 51, 51));
        btnSubMenuOrganizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSubMenuOrganizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMenuOrganizacionActionPerformed(evt);
            }
        });
        panelInterno.add(btnSubMenuOrganizacion);

        subMenuConfiguracion.setBackground(new java.awt.Color(229, 231, 235));
        subMenuConfiguracion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        subMenuConfiguracion.setForeground(new java.awt.Color(51, 51, 51));
        subMenuConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subMenuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuConfiguracionActionPerformed(evt);
            }
        });
        panelInterno.add(subMenuConfiguracion);

        scrollMenu.setViewportView(panelInterno);

        pnlMenu.add(scrollMenu);

        barraLateral.add(pnlMenu, java.awt.BorderLayout.CENTER);

        piePagina.setBackground(new java.awt.Color(229, 231, 235));
        piePagina.setForeground(new java.awt.Color(0, 0, 0));
        piePagina.setPreferredSize(new java.awt.Dimension(280, 110));
        piePagina.setLayout(new javax.swing.BoxLayout(piePagina, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        piePagina.add(jLabel3);

        jLabel4.setText("jLabel4");
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 100));
        piePagina.add(jLabel4);

        barraLateral.add(piePagina, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(barraLateral, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignacionesActionPerformed

    private void btnSubMenuOrganizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMenuOrganizacionActionPerformed
        int indexBoton = 4;

        if (!menuDesplegado) {
            this.panelInterno.add(btnEmpresa, indexBoton + 1);
            this.panelInterno.add(btnSucursal, indexBoton + 2);
            this.panelInterno.add(btnDepartamento, indexBoton + 3);
            this.panelInterno.add(btnPuesto, indexBoton + 4);

            menuDesplegado = true;
        } else {
            this.panelInterno.remove(btnEmpresa);
            this.panelInterno.remove(btnSucursal);
            this.panelInterno.remove(btnDepartamento);
            this.panelInterno.remove(btnPuesto);

            menuDesplegado = false;
        }

        this.panelInterno.revalidate();
        this.panelInterno.repaint();
    }//GEN-LAST:event_btnSubMenuOrganizacionActionPerformed

    private void subMenuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuConfiguracionActionPerformed
        int indexBoton = 5;
        
        if (menuDesplegado == true ) {
            indexBoton = 9;
        }

        if (!menuDesplegado2) {
            this.panelInterno.add(btnUsuario, indexBoton + 1);
            this.panelInterno.add(btnAuditoria, indexBoton + 2);

            menuDesplegado2 = true;
        } else {
            this.panelInterno.remove(btnUsuario);
            this.panelInterno.remove(btnAuditoria);

            menuDesplegado2 = false;
        }

        this.panelInterno.revalidate();
        this.panelInterno.repaint();
    }//GEN-LAST:event_subMenuConfiguracionActionPerformed

    /**
     * Configura el comportamiento visual completo del botón (Hover, Click,
     * Selección).
     *
     * @param boton El botón a configurar.
     * @param rutaIcono La ruta del SVG (necesaria para repintarlo de
     * blanco/negro).
     */
    private void configurarBotonMenu(JButton boton, String rutaIcono) {

        boton.setBackground(COLOR_NORMAL);
        boton.setForeground(COLOR_TEXT_NORMAL);
        boton.setIcon(crearIconoColoreado(rutaIcono, 25, 25, COLOR_TEXT_NORMAL));
        boton.setBorder(new EmptyBorder(0, 10, 0, 0));
        boton.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                if (boton != botonActual) {
                    boton.setBackground(COLOR_HOVER);
                    boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (boton != botonActual) {
                    boton.setBackground(COLOR_NORMAL);
                }
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (botonActual != null && botonActual != boton) {
                    resetearEstiloBoton(botonActual);
                }

                botonActual = boton;
                boton.setBackground(COLOR_SELECTED_BG);
                boton.setForeground(COLOR_SELECTED_FG);
                boton.setIcon(crearIconoColoreado(rutaIcono, 25, 25, COLOR_SELECTED_FG));
            }
        });
    }

    private void resetearEstiloBoton(JButton boton) {
        boton.setBackground(COLOR_NORMAL);
        boton.setForeground(COLOR_TEXT_NORMAL);

        String ruta = (String) boton.getClientProperty("rutaIcono");
        if (ruta != null) {
            boton.setIcon(crearIconoColoreado(ruta, 25, 25, COLOR_TEXT_NORMAL));
        }
    }

    /**
     * Crea un icono SVG y fuerza que sea de un color específico.
     *
     * @param ruta Ruta dentro de resources (ej: "iconos/usuario.svg")
     * @param ancho Ancho deseado
     * @param alto Alto deseado2
     * @param colorDeseado El color que quieres (ej: Color.RED, Color.BLUE)
     * @return El icono coloreado listo para usar.
     */
    public FlatSVGIcon crearIconoColoreado(String ruta, int ancho, int alto, Color colorDeseado) {

        FlatSVGIcon icono = new FlatSVGIcon(ruta, ancho, alto);

        icono.setColorFilter(new FlatSVGIcon.ColorFilter(c -> {
            return colorDeseado;
        }));

        return icono;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnAsignaciones;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnSubMenuOrganizacion;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelInterno;
    private javax.swing.JPanel piePagina;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JScrollPane scrollMenu;
    private javax.swing.JButton subMenuConfiguracion;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
